[package]
name = "mcapable-opendal"
version = "0.1.0"
edition = "2024"

[dependencies]
mcapable-core = { path = "../mcapable-core" }
bytes = "1.11"
opendal = { version = "0.49", features = ["layers-blocking", "services-gcs", "services-http", "services-s3"] }
url = "2.5"

[dev-dependencies]
aws-config = "1.6"
aws-credential-types = "1.2"
aws-sdk-s3 = "1.57"
base64 = "0.22"
testcontainers = { version = "0.16", features = ["blocking"] }
tokio = { version = "1.39", features = ["macros", "rt-multi-thread", "time"] }
