[package]
name = "mcapable-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "mcapable"
crate-type = ["cdylib"]

[dependencies]
mcapable-core = { path = "../mcapable-core", features = ["parsers"] }
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py38"] }
bytes = "1.11"
serde_json = "1.0"
