load("@crate_index//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "mcapable",
    crate_name = "mcapable",
    crate_root = "src/lib.rs",
    srcs = glob(["src/**/*.rs", "src/*.rs"]),
    edition = "2024",
    aliases = aliases(),
    deps = all_crate_deps(
        normal = True,
    ) + [
        "//crates/mcapable-core:core",
    ],
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
)
